name: sikomik_bloc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter_rating_bar: ^4.0.1
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.12
  flutter_bloc: ^9.0.0
  flutter_inappwebview: ^6.1.5
  flutter_image: ^4.1.12
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.2.1
  responsive_framework: ^1.5.1
  toastification: ^3.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  rename_app: ^1.6.2

flutter:
  uses-material-design: true

  assets:
    - images/