// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfAFyo-4GrODqRV6YUHe3EnkepaEk4XcE',
    appId: '1:504193950692:web:570c136f46408d9d1fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    authDomain: 'sikomik-86156.firebaseapp.com',
    storageBucket: 'sikomik-86156.firebasestorage.app',
    measurementId: 'G-4QB1BW99S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLqjzbgyz9IZDMERjP_pIq_b0SqZA6QE',
    appId: '1:504193950692:android:0f4389b1dd4efc481fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    storageBucket: 'sikomik-86156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5eUmhjxTFN_6XW3qNnxOW2uZ8eY-aGMI',
    appId: '1:504193950692:ios:6dee3385fff7bfd21fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    storageBucket: 'sikomik-86156.firebasestorage.app',
    androidClientId: '504193950692-juj7uknam85pa798sukp2k305p9j0kk9.apps.googleusercontent.com',
    iosClientId: '504193950692-mrvtl1q4i2keb2tk9914vi57tp53gger.apps.googleusercontent.com',
    iosBundleId: 'com.sempatpanick.sikomikBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5eUmhjxTFN_6XW3qNnxOW2uZ8eY-aGMI',
    appId: '1:504193950692:ios:6dee3385fff7bfd21fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    storageBucket: 'sikomik-86156.firebasestorage.app',
    androidClientId: '504193950692-juj7uknam85pa798sukp2k305p9j0kk9.apps.googleusercontent.com',
    iosClientId: '504193950692-mrvtl1q4i2keb2tk9914vi57tp53gger.apps.googleusercontent.com',
    iosBundleId: 'com.sempatpanick.sikomikBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRGqjNakpLVE_G7mEusaEOKOHftgegksk',
    appId: '1:504193950692:web:48b96e8d812924031fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    authDomain: 'sikomik-86156.firebaseapp.com',
    storageBucket: 'sikomik-86156.firebasestorage.app',
    measurementId: 'G-HM6NTT482S',
  );

}