// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfAFyo-4GrODqRV6YUHe3EnkepaEk4XcE',
    appId: '1:504193950692:web:570c136f46408d9d1fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    authDomain: 'sikomik-86156.firebaseapp.com',
    storageBucket: 'sikomik-86156.appspot.com',
    measurementId: 'G-4QB1BW99S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLqjzbgyz9IZDMERjP_pIq_b0SqZA6QE',
    appId: '1:504193950692:android:3f6013d5d89c78a21fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    storageBucket: 'sikomik-86156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5eUmhjxTFN_6XW3qNnxOW2uZ8eY-aGMI',
    appId: '1:504193950692:ios:bc2450abc2af61db1fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    storageBucket: 'sikomik-86156.appspot.com',
    androidClientId: '504193950692-juj7uknam85pa798sukp2k305p9j0kk9.apps.googleusercontent.com',
    iosClientId: '504193950692-b4f98vtjom5l2d752vv2spfrnuoo58nq.apps.googleusercontent.com',
    iosBundleId: 'com.sempatpanick.sikomik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5eUmhjxTFN_6XW3qNnxOW2uZ8eY-aGMI',
    appId: '1:504193950692:ios:bc2450abc2af61db1fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    storageBucket: 'sikomik-86156.appspot.com',
    androidClientId: '504193950692-juj7uknam85pa798sukp2k305p9j0kk9.apps.googleusercontent.com',
    iosClientId: '504193950692-b4f98vtjom5l2d752vv2spfrnuoo58nq.apps.googleusercontent.com',
    iosBundleId: 'com.sempatpanick.sikomik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfAFyo-4GrODqRV6YUHe3EnkepaEk4XcE',
    appId: '1:504193950692:web:ced68378e10f817e1fddf1',
    messagingSenderId: '504193950692',
    projectId: 'sikomik-86156',
    authDomain: 'sikomik-86156.firebaseapp.com',
    storageBucket: 'sikomik-86156.appspot.com',
    measurementId: 'G-LB82WWGSL2',
  );

}