name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cirruslabs/flutter:stable

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Clean Dependencies
      run: flutter clean

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web --wasm --release

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/web/
        server-dir: /
